[workspace]
members = [
    "eventually",
    "eventually-core",
    "eventually-postgres",
    "eventually-redis",
    "eventually-util",

    # Example cases
    "examples/orders-domain",
    "examples/orders-http-api-postgres-store"
]
